version: '3.9'
services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - '8000:8000'
  api:
    build: ./apps/api
    volumes:
      - ./apps/api:/app
    environment:
      TABLE_NAME: expo-pwa-table
    ports:
      - '3000:3000'
  frontend:
    build: ./apps/frontend
    volumes:
      - ./apps/frontend:/app
    ports:
      - '5173:5173'
